# Generated by Django 5.1.7 on 2025-06-12 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email_campaing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email кампанія', 'verbose_name_plural': 'Email кампанії'},
        ),
        migrations.AddField(
            model_name='email_campaing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='email_campaing',
            name='status',
            field=models.CharField(choices=[('send', 'Відправлено'), ('not sent', 'Не відправлено')], default='not sent', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='email_campaing',
            name='text',
            field=models.TextField(verbose_name='Текст листа'),
        ),
        migrations.AlterField(
            model_name='email_campaing',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Користувачі'),
        ),
    ]
