# Generated by Django 5.1.7 on 2025-06-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_email_campaing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamplate_email',
            options={'verbose_name': 'Шаблон email', 'verbose_name_plural': 'Шаблони email'},
        ),
        migrations.RemoveField(
            model_name='email_campaing',
            name='text',
        ),
        migrations.AlterField(
            model_name='tamplate_email',
            name='email_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.email_campaing', verbose_name='Email Кампанія'),
        ),
        migrations.AlterField(
            model_name='tamplate_email',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tamplate_email',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
