# Generated by Django 5.1.7 on 2025-06-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tamplate_email_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_campaing',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tamplate_email', verbose_name='Шаблон Email'),
        ),
        migrations.AlterField(
            model_name='tamplate_email',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_templates', to='users.email_campaing', verbose_name='Email Кампанія'),
        ),
    ]
