# Generated by Django 5.1.7 on 2025-06-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_email_campaing_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamplate_email',
            name='title',
        ),
    ]
