# Generated by Django 5.1.7 on 2025-06-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tamplate_email_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tamplate_email',
            options={'verbose_name': 'Шаблон email', 'verbose_name_plural': 'Шаблоны email'},
        ),
        migrations.RemoveField(
            model_name='tamplate_email',
            name='text',
        ),
        migrations.AddField(
            model_name='tamplate_email',
            name='template_file',
            field=models.FileField(default=12, upload_to='email_templates/', verbose_name='Файл шаблона Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tamplate_email',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_templates', to='users.email_campaing', verbose_name='Email Кампания'),
        ),
    ]
