services:
  web:
    build:
      context: /root/CinemaCMS
      dockerfile: Dockerfile
    command:
      - uvicorn
      - cinewave.asgi:application
      - --host
      - 0.0.0.0
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
    networks:
      - app-network
    volumes:
      - /root/CinemaCMS:/app
      - /root/CinemaCMS/static_collected:/app/static_collected
      - /root/CinemaCMS/media:/app/media
  celery_worker:
    build:
      context: /root/CinemaCMS
      dockerfile: Dockerfile
    command: celery -A cinewave worker -l info
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
      - web
    networks:
      - app-network
    volumes:
      - /root/CinemaCMS:/app