

services:
  web:
    volumes:
      - ./media:/app/media

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media:ro
      - ./static_collected:/app/static_collected:ro