# Generated by Django 5.2 on 2025-04-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('conditions', models.TextField(verbose_name='Умови')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатри',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='core.cinemas', verbose_name='Кинотеатр')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('time_session', models.TimeField(verbose_name='Час сеансу')),
                ('duration', models.TimeField(verbose_name='Тривалість')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movies')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_row', models.IntegerField(verbose_name='Номер ряда')),
                ('seat', models.IntegerField(verbose_name='Номер місця')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('S', 'Куплене'), ('F', 'Вільне'), ('N', 'Не доступно')], default='F', max_length=12, verbose_name='Статус місця')),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessions', verbose_name='сеанс')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
    ]
