# Generated by Django 5.1.7 on 2025-04-14 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('conditions', models.TextField(verbose_name='Умови')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='SEO блок')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатри',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='core.cinemas', verbose_name='Кинотеатр')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11, verbose_name='Жанр ')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('url_trailer', models.URLField(verbose_name='URL трелера ')),
                ('description', models.TextField(verbose_name='Опис ')),
                ('video_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('imax', 'IMAX')], max_length=5, verbose_name='Тип відео ')),
                ('relise_date', models.DateField(verbose_name='Дата проката')),
                ('age_limit', models.IntegerField(verbose_name='Вікова категорія')),
                ('date', models.DateField(verbose_name='Дата')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='main.gallery', verbose_name='Галерея')),
                ('main_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_movies', to='main.picture', verbose_name='Головне зображення')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Стрічка',
                'verbose_name_plural': 'Стрічки',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('time_session', models.TimeField(verbose_name='Час сеансу')),
                ('duration', models.TimeField(verbose_name='Тривалість')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movies', verbose_name='Кіно')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеанси',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_row', models.IntegerField(verbose_name='Номер ряда')),
                ('seat', models.IntegerField(verbose_name='Номер місця')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('S', 'Куплене'), ('F', 'Вільне'), ('N', 'Не доступно')], default='F', max_length=12, verbose_name='Статус місця')),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessions', verbose_name='сеанс')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Глядач')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.seats', verbose_name='місце')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.sessions', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
    ]
