# Generated by Django 5.1.7 on 2025-04-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', 'Куплене'), ('F', 'Вільне'), ('N', 'Не доступно')], default='F', max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture')),
            ],
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('conditions', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo')),
                ('halls_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('url_trailer', models.URLField()),
                ('description', models.TextField()),
                ('video_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('imax', 'IMAX')], max_length=5)),
                ('relise_date', models.DateField()),
                ('age_limit', models.IntegerField()),
                ('date', models.DateField()),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('time_session', models.TimeField()),
                ('duration', models.TimeField()),
                ('date', models.DateField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessions')),
            ],
        ),
    ]
