# Generated by Django 5.1.7 on 2025-06-29 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Глядач'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.seats', verbose_name='місце'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.sessions', verbose_name='Сеанс'),
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('halls', 'number_row', 'seat')},
        ),
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.UniqueConstraint(fields=('session', 'seat'), name='unique_ticket_session_seat'),
        ),
    ]
