# Generated by Django 5.1.7 on 2025-04-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='seo_block',
        ),
    ]
