# Generated by Django 5.1.7 on 2025-04-02 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemas',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='halls_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls'),
        ),
        migrations.AddField(
            model_name='movies',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movies'),
        ),
        migrations.AddField(
            model_name='seats',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessions'),
        ),
    ]
