# Generated by Django 5.1.7 on 2025-04-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movies_main_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='main_picture',
        ),
    ]
