# Generated by Django 5.1.7 on 2025-04-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('main', '0002_alter_baners_options_alter_block_seo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name': 'Кинотеатр', 'verbose_name_plural': 'Кинотеатри'},
        ),
        migrations.AlterModelOptions(
            name='halls',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='seats',
            options={'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеанси'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Квиток', 'verbose_name_plural': 'Квитки'},
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='conditions',
            field=models.TextField(verbose_name='Умови'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='halls_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Картинки'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='SEO блок'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
