# Generated by Django 5.1.7 on 2025-04-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tickets_profile_tickets_seat_tickets_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.cinemas', verbose_name='Кинотеатр'),
            preserve_default=False,
        ),
    ]
