# Generated by Django 5.1.7 on 2025-04-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movies_gallery_remove_movies_seo_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='movie_id',
        ),
    ]
