# Generated by Django 5.1.7 on 2025-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessions_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість рядів'),
        ),
        migrations.AddField(
            model_name='halls',
            name='seats_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Місць у ряду'),
        ),
    ]
