# Generated by Django 5.1.7 on 2025-04-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sessions_movie_id'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movies'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
