# Generated by Django 5.1.7 on 2025-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sessions_hall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='price',
            field=models.PositiveIntegerField(default=55, verbose_name='Цена'),
        ),
    ]
