# Generated by Django 5.1.7 on 2025-04-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cinemas_options_alter_halls_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemas',
            name='halls_id',
        ),
        migrations.AddField(
            model_name='halls',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='core.cinemas', verbose_name='Кинотеатр'),
            preserve_default=False,
        ),
    ]
