# Generated by Django 5.1.7 on 2025-04-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_movies_main_picture'),
        ('main', '0003_remove_gallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='main_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_movies', to='main.picture', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='main.gallery', verbose_name='Галерея зображень'),
        ),
    ]
