# Generated by Django 5.1.7 on 2025-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sessions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=8, null=True, verbose_name='Ціна'),
        ),
    ]
