# Generated by Django 5.1.7 on 2025-04-09 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cinemas_halls_id_halls_cinema'),
        ('main', '0003_alter_block_seo_options_alter_baners_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halls',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Зали'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Стрічка', 'verbose_name_plural': 'Стрічки'},
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
        migrations.AddField(
            model_name='seats',
            name='status',
            field=models.CharField(choices=[('S', 'Куплене'), ('F', 'Вільне'), ('N', 'Не доступно')], default='F', max_length=12, verbose_name='Статус місця'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age_limit',
            field=models.IntegerField(verbose_name='Вікова категорія'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(verbose_name='Опис '),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11, verbose_name='Жанр '),
        ),
        migrations.AlterField(
            model_name='movies',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='relise_date',
            field=models.DateField(verbose_name='Дата проката'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО '),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_trailer',
            field=models.URLField(verbose_name='URL трелера '),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video_type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('imax', 'IMAX')], max_length=5, verbose_name='Тип відео '),
        ),
        migrations.AlterField(
            model_name='seats',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='number_row',
            field=models.IntegerField(verbose_name='Номер ряда'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='seat',
            field=models.IntegerField(verbose_name='Номер місця'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessions', verbose_name='сеанс'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='duration',
            field=models.TimeField(verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movies', verbose_name='Кіно'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_session',
            field=models.TimeField(verbose_name='Час сеансу'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Глядач'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.seats', verbose_name='місце'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.sessions', verbose_name='Сеанс'),
        ),
    ]
