# Generated by Django 5.1.7 on 2025-05-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_halls_rows_halls_seats_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AddField(
            model_name='seats',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='number_row',
            field=models.IntegerField(verbose_name='Номер ряду'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessions', verbose_name='Сеанс'),
        ),
    ]
