# Generated by Django 5.1.7 on 2025-04-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movies_main_picture_alter_movies_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='main_picture',
        ),
    ]
