# Generated by Django 5.1.7 on 2025-04-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movies_main_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Кіно стрічка', 'verbose_name_plural': 'Кіно стрічки'},
        ),
    ]
