# Generated by Django 5.1.7 on 2025-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seats_is_vip_seats_price_alter_seats_number_row_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='title',
        ),
    ]
