# Generated by Django 5.1.7 on 2025-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_seats_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.CharField(choices=[('S', 'Куплене'), ('b', 'Заброньоване'), ('F', 'Вільне'), ('N', 'Не доступно')], default='F', max_length=1, verbose_name='Статус місця'),
        ),
    ]
