# Generated by Django 5.1.7 on 2025-05-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sessions_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='session_id',
        ),
    ]
