# Generated by Django 5.1.7 on 2025-05-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_seats_session_id'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movies'),
        ),
    ]
