# Generated by Django 5.1.7 on 2025-04-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tickets_halls'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='halls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.halls', verbose_name='Зал'),
            preserve_default=False,
        ),
    ]
