# Generated by Django 5.1.7 on 2025-05-03 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tickets_profile'),
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.UniqueConstraint(fields=('session', 'seat'), name='unique_ticket_session_seat'),
        ),
    ]
