# Generated by Django 5.1.7 on 2025-05-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tickets_unique_ticket_session_seat'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_sessions', to='movie.movies'),
        ),
    ]
