# Generated by Django 5.1.7 on 2025-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sessions_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата та час покупки'),
        ),
    ]
