# Generated by Django 5.1.7 on 2025-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tickets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemas',
            name='city_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='city_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='conditions_ru',
            field=models.TextField(null=True, verbose_name='Умови'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='conditions_uk',
            field=models.TextField(null=True, verbose_name='Умови'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='halls',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='halls',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='halls',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='halls',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
    ]
