# Generated by Django 5.1.7 on 2025-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cinemas_city_ru_cinemas_city_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='scheme_hall',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема залу'),
        ),
    ]
