# Generated by Django 5.1.7 on 2025-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cinemas_city_ru_cinemas_city_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halls',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='halls',
            name='seats_row',
        ),
        migrations.AddField(
            model_name='halls',
            name='scheme_hall',
            field=models.FileField(default=222, upload_to='scheme_hall/'),
            preserve_default=False,
        ),
    ]
