# Generated by Django 5.1.7 on 2025-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_halls_scheme_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='scheme_hall',
            field=models.FileField(default=1, upload_to='hall_schemes/'),
            preserve_default=False,
        ),
    ]
