# Generated by Django 5.1.7 on 2025-06-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_halls_scheme_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halls',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='halls',
            name='seats_row',
        ),
    ]
