# Generated by Django 5.1.7 on 2025-06-16 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_halls_rows_remove_halls_seats_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seats',
            options={'ordering': ['number_row', 'seat'], 'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterField(
            model_name='seats',
            name='halls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats_in_hall', to='core.halls', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='status',
            field=models.CharField(choices=[('S', 'Куплене'), ('F', 'Вільне'), ('N', 'Не доступно')], default='F', max_length=1, verbose_name='Статус місця'),
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('halls', 'number_row', 'seat')},
        ),
    ]
