# Generated by Django 5.1.7 on 2025-06-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_seats_options_alter_seats_halls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='scheme_hall',
            field=models.FileField(upload_to='scheme_hall/'),
        ),
    ]
