# Generated by Django 5.2 on 2025-04-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_SEO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_seo', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('seo_url', models.SlugField(unique=True, verbose_name='URL адреса ')),
                ('seo_text', models.TextField(blank=True, verbose_name='текст')),
                ('seo_keywords', models.CharField(blank=True, max_length=250, verbose_name='Ключові слова')),
                ('seo_description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Блок СЕО',
                'verbose_name_plural': 'Блоки СЕО',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Опис ')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса ')),
                ('latitude', models.FloatField(verbose_name='Довгота ')),
                ('longitude', models.FloatField(verbose_name='Широта ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Назва галереї')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереї',
            },
        ),
        migrations.CreateModel(
            name='Cross_banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('photo_background', 'фото на фоне'), ('photo', 'просто фото')])),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Сквозной Банер',
                'verbose_name_plural': 'Сквозние Банери',
            },
        ),
        migrations.CreateModel(
            name='Baners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL адреса ')),
                ('text', models.CharField(max_length=100, verbose_name='текст')),
                ('scroll_speed', models.DurationField(verbose_name='Швидкість прокрутки (сек.)')),
                ('type', models.CharField(choices=[('baner_top', 'Сквозной банер'), ('news', 'новости')], max_length=100, verbose_name='ТИп')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показувати ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
            },
        ),
        migrations.CreateModel(
            name='MainPaiges',
            fields=[
                ('name_cinema', models.CharField(max_length=250, verbose_name='Кинотеатр')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SEO_text', models.TextField(verbose_name='Сео текст ')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головні сторінки',
            },
        ),
        migrations.CreateModel(
            name='PaigesCinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Показ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
            },
        ),
        migrations.CreateModel(
            name='PaigesNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('url', models.URLField(verbose_name='URL адреса ')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Показ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Сторінка Новини',
                'verbose_name_plural': 'Сторінки Новин',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('main_picture', 'Главное изображение'), ('gallery', 'Галерея'), ('baner', 'Банер'), ('cross_baner', 'Сквозной банер')], max_length=20, verbose_name='Тип зображення')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Зображення')),
                ('alter_txt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативний текст')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Опис ')),
                ('description', models.TextField(verbose_name='Опис')),
                ('url_video', models.URLField(verbose_name='URL адреса ')),
                ('date_publication', models.DateField(verbose_name='Дата ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
            },
        ),
    ]
