# Generated by Django 5.1.7 on 2025-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Назва галереї'),
            preserve_default=False,
        ),
    ]
