# Generated by Django 5.1.7 on 2025-05-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL адреса ')),
                ('text', models.CharField(max_length=100, verbose_name='текст')),
                ('scroll_speed', models.DurationField(verbose_name='Швидкість прокрутки (сек.)')),
                ('type', models.CharField(choices=[('baner_top', 'Сквозной банер'), ('news', 'новости')], max_length=100, verbose_name='Тbп')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показувати ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
            },
        ),
        migrations.DeleteModel(
            name='Baners',
        ),
    ]
