# Generated by Django 5.1.7 on 2025-04-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
    ]
