# Generated by Django 5.1.7 on 2025-04-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baners',
            options={'verbose_name': 'Банер', 'verbose_name_plural': 'Банери'},
        ),
        migrations.AlterModelOptions(
            name='block_seo',
            options={'verbose_name': 'Блок СЕО', 'verbose_name_plural': 'Бблоки СЕО'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='paigescinema',
            options={'verbose_name': 'Сторінка', 'verbose_name_plural': 'Сторінки'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акція', 'verbose_name_plural': 'Акції'},
        ),
    ]
