# Generated by Django 5.1.7 on 2025-05-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners_delete_baners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='alter_txt',
        ),
        migrations.AlterField(
            model_name='banners',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='main.gallery', verbose_name='Картинка'),
        ),
    ]
