# Generated by Django 5.1.7 on 2025-04-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_baners_options_alter_block_seo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block_seo',
            options={'verbose_name': 'Блок СЕО', 'verbose_name_plural': 'Блоки СЕО'},
        ),
        migrations.AlterField(
            model_name='baners',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Показувати '),
        ),
        migrations.AlterField(
            model_name='baners',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='baners',
            name='scroll_speed',
            field=models.TimeField(verbose_name='Швидкість прокрутки'),
        ),
        migrations.AlterField(
            model_name='baners',
            name='text',
            field=models.CharField(max_length=100, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='baners',
            name='type',
            field=models.CharField(max_length=100, verbose_name='ТИп'),
        ),
        migrations.AlterField(
            model_name='baners',
            name='url',
            field=models.URLField(verbose_name='URL адреса '),
        ),
        migrations.AlterField(
            model_name='block_seo',
            name='seo_description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='block_seo',
            name='seo_keywords',
            field=models.CharField(max_length=250, verbose_name='Ключові слова'),
        ),
        migrations.AlterField(
            model_name='block_seo',
            name='seo_text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='block_seo',
            name='seo_url',
            field=models.SlugField(verbose_name='URL адреса '),
        ),
        migrations.AlterField(
            model_name='block_seo',
            name='title_seo',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адреса '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(verbose_name='Довгота '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(verbose_name='Широта '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paigescinema', verbose_name='Сторінка '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Опис '),
        ),
        migrations.AlterField(
            model_name='paigescinema',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='paigescinema',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Показ'),
        ),
        migrations.AlterField(
            model_name='paigescinema',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Зображення '),
        ),
        migrations.AlterField(
            model_name='paigescinema',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО '),
        ),
        migrations.AlterField(
            model_name='picture',
            name='alter_txt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативний текст'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_type',
            field=models.CharField(choices=[('main_picture', 'Главное изображение'), ('gallery', 'Галерея')], max_length=20, verbose_name='Тип зображення'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date_publication',
            field=models.DateField(verbose_name='Дата '),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Зображення '),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО '),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url_video',
            field=models.URLField(verbose_name='URL адреса '),
        ),
    ]
