# Generated by Django 5.1.7 on 2025-04-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gallery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
