# Generated by Django 5.1.7 on 2025-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baners',
            name='scroll_speed',
            field=models.DurationField(verbose_name='Швидкість прокрутки (сек.)'),
        ),
    ]
