# Generated by Django 5.1.7 on 2025-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_gallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default=33, max_length=250, verbose_name='Фильм'),
            preserve_default=False,
        ),
    ]
