# Generated by Django 5.1.7 on 2025-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_picture_alter_txt_alter_banners_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_type',
            field=models.CharField(choices=[('main_picture', 'Главное изображение'), ('gallery', 'Галерея')], max_length=20, verbose_name='Тип зображення'),
        ),
    ]
