# Generated by Django 5.1.7 on 2025-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_picture_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.AlterField(
            model_name='banners',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Показувати'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='type',
            field=models.CharField(choices=[('baner_top', 'Сквозной банер'), ('news', 'новости')], default='baner_top', max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='url',
            field=models.URLField(verbose_name='URL адреса'),
        ),
    ]
