# Generated by Django 5.1.7 on 2025-04-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_picture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paigescinema',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Назва'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baners',
            name='type',
            field=models.CharField(choices=[('baner_top', 'Сквозной банер'), ('news', 'новости')], max_length=100, verbose_name='ТИп'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_type',
            field=models.CharField(choices=[('main_picture', 'Главное изображение'), ('gallery', 'Галерея'), ('baner', 'Банер')], max_length=20, verbose_name='Тип зображення'),
        ),
        migrations.CreateModel(
            name='Cross_banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('photo_background', 'фото на фоне'), ('photo', 'просто фото')])),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Сквозной Банер',
                'verbose_name_plural': 'Сквозние Банери',
            },
        ),
        migrations.CreateModel(
            name='MainPaiges',
            fields=[
                ('name_cinema', models.CharField(max_length=250, verbose_name='Кинотеатр')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SEO_text', models.TextField(verbose_name='Сео текст ')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Сторінка Новини',
                'verbose_name_plural': 'Сторінки Новин',
            },
        ),
        migrations.CreateModel(
            name='PaigesNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('url', models.URLField(verbose_name='URL адреса ')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Показ')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gallery', verbose_name='Картинка')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Сторінка Новини',
                'verbose_name_plural': 'Сторінки Новин',
            },
        ),
    ]
