# Generated by Django 5.1.7 on 2025-04-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paigescinema_title_alter_baners_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpaiges',
            options={'verbose_name': 'Головна сторінка', 'verbose_name_plural': 'Головні сторінки'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Опис '),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='picture',
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='main.picture', verbose_name='Зображення'),
            preserve_default=False,
        ),
    ]
