# Generated by Django 5.1.7 on 2025-05-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gallery_title_alter_banners_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.gallery', verbose_name='Картинка'),
        ),
    ]
