# Generated by Django 5.1.7 on 2025-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_banners_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='scroll_speed',
            field=models.DurationField(blank=True, null=True, verbose_name='Швидкість прокрутки (сек.)'),
        ),
    ]
