# Generated by Django 5.1.7 on 2025-05-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banners_scroll_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cross_banner',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gallery', verbose_name='Картинка'),
        ),
    ]
