# Generated by Django 5.1.7 on 2025-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_gallery_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='picture',
        ),
        migrations.AddField(
            model_name='gallery',
            name='picture',
            field=models.ManyToManyField(related_name='galleries', to='main.picture', verbose_name='Зображення'),
        ),
    ]
