# Generated by Django 5.1.7 on 2025-05-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cross_banner_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='type',
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL адреса')),
                ('scroll_speed', models.DurationField(blank=True, null=True, verbose_name='Швидкість прокрутки (сек.)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показувати')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.gallery', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
            },
        ),
    ]
