# Generated by Django 5.1.7 on 2025-05-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_banners_type_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cross_banner',
            name='type',
            field=models.CharField(choices=[('photo_background', 'Фото на фоне'), ('photo', 'Просто фото')], default='photo_background', max_length=50, verbose_name='Тип банера'),
        ),
    ]
