# Generated by Django 5.1.7 on 2025-05-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cross_banner_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL адреса'),
        ),
    ]
