# Generated by Django 5.1.7 on 2025-05-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_news_options_news_text_alter_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
    ]
