# Generated by Django 5.1.7 on 2025-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_news_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL адреса'),
        ),
    ]
