# Generated by Django 5.1.7 on 2025-05-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_banners_text_alter_banners_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Банер', 'verbose_name_plural': 'Банери'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='text',
            field=models.CharField(max_length=100, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='url',
            field=models.URLField(verbose_name='URL адреса'),
        ),
        migrations.AlterField(
            model_name='cross_banner',
            name='type',
            field=models.CharField(choices=[('photo_background', 'фото на фоне'), ('photo', 'просто фото')]),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(verbose_name='URL адреса'),
        ),
    ]
