# Generated by Django 5.1.7 on 2025-05-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_news_options_alter_banners_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
