# Generated by Django 5.1.7 on 2025-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_type',
            field=models.CharField(choices=[('main_picture', 'Головне зображення'), ('gallery', 'Галерея'), ('logo', 'Логотип')], max_length=20, verbose_name='Тип зображення'),
        ),
    ]
