# Generated by Django 5.1.7 on 2025-06-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_picture_image_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL адреса'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL адреса'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_type',
            field=models.CharField(choices=[('main_picture', 'Главное изображение'), ('gallery', 'Галерея'), ('logo', 'Лого')], max_length=20, verbose_name='Тип зображення'),
        ),
    ]
