# Generated by Django 5.1.7 on 2025-06-04 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_news_options_alter_banners_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='date_publication',
        ),
        migrations.AddField(
            model_name='promotion',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='paigesnews',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата публікації'),
        ),
    ]
