# Generated by Django 5.1.7 on 2025-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_promotion_date_publication_promotion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Показ'),
        ),
    ]
