# Generated by Django 5.1.7 on 2025-06-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_promotion_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block_seo',
            name='seo_text',
        ),
    ]
