# Generated by Django 5.1.7 on 2025-06-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_block_seo_seo_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpaiges',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='mainpaiges',
            name='name_cinema',
        ),
    ]
