# Generated by Django 5.1.7 on 2025-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_mainpaiges_gallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpaiges',
            old_name='phone',
            new_name='phone_1',
        ),
        migrations.AddField(
            model_name='mainpaiges',
            name='phone_2',
            field=models.CharField(default=131342, max_length=16, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
