# Generated by Django 5.1.7 on 2025-06-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_phone_mainpaiges_phone_1_mainpaiges_phone_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='main.gallery', verbose_name='Картинка'),
        ),
    ]
