# Generated by Django 5.1.7 on 2025-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_contact_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта '),
        ),
    ]
