# Generated by Django 5.1.7 on 2025-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_contact_latitude_alter_contact_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seo_block',
            field=models.ManyToManyField(to='main.block_seo', verbose_name='Блок СЕО '),
        ),
    ]
