# Generated by Django 5.1.7 on 2025-06-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_contact_seo_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='seo_block',
        ),
        migrations.AddField(
            model_name='contact',
            name='seo_block',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО '),
            preserve_default=False,
        ),
    ]
