# Generated by Django 5.1.7 on 2025-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_contact_seo_block_contact_seo_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpaiges',
            name='SEO_text_ru',
            field=models.TextField(null=True, verbose_name='Сео текст '),
        ),
        migrations.AddField(
            model_name='mainpaiges',
            name='SEO_text_uk',
            field=models.TextField(null=True, verbose_name='Сео текст '),
        ),
        migrations.AddField(
            model_name='mainpaiges',
            name='phone_1_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='mainpaiges',
            name='phone_1_uk',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='mainpaiges',
            name='phone_2_ru',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='mainpaiges',
            name='phone_2_uk',
            field=models.CharField(max_length=16, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='paigescinema',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='paigescinema',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='paigescinema',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='paigescinema',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='paigesnews',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='paigesnews',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='paigesnews',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='paigesnews',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Опис '),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Опис '),
        ),
    ]
