# Generated by Django 5.1.7 on 2025-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_mainpaiges_seo_text_ru_mainpaiges_seo_text_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpaiges',
            name='SEO_text',
            field=models.TextField(verbose_name='СЕО текст '),
        ),
        migrations.AlterField(
            model_name='mainpaiges',
            name='SEO_text_ru',
            field=models.TextField(null=True, verbose_name='СЕО текст '),
        ),
        migrations.AlterField(
            model_name='mainpaiges',
            name='SEO_text_uk',
            field=models.TextField(null=True, verbose_name='СЕО текст '),
        ),
    ]
