# Generated by Django 5.2 on 2025-04-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11, verbose_name='Жанр ')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('url_trailer', models.URLField(verbose_name='URL трелера ')),
                ('description', models.TextField(verbose_name='Опис ')),
                ('video_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('imax', 'IMAX')], max_length=5, verbose_name='Тип відео ')),
                ('relise_date', models.DateField(verbose_name='Дата проката')),
                ('age_limit', models.IntegerField(verbose_name='Вікова категорія')),
                ('date', models.DateField(verbose_name='Дата')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='main.gallery', verbose_name='Галерея зображень')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Кіно стрічка',
                'verbose_name_plural': 'Кіно стрічки',
            },
        ),
    ]
