# Generated by Django 5.1.7 on 2025-07-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11, verbose_name='Жанр ')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('url_trailer', models.URLField(verbose_name='URL трейлера')),
                ('description', models.TextField(verbose_name='Опис')),
                ('description_ru', models.TextField(null=True, verbose_name='Опис')),
                ('description_uk', models.TextField(null=True, verbose_name='Опис')),
                ('relise_date', models.DateField(verbose_name='Дата проката')),
                ('relise_date_ru', models.DateField(null=True, verbose_name='Дата проката')),
                ('relise_date_uk', models.DateField(null=True, verbose_name='Дата проката')),
                ('age_limit', models.IntegerField(verbose_name='Вікова категорія')),
                ('age_limit_ru', models.IntegerField(null=True, verbose_name='Вікова категорія')),
                ('age_limit_uk', models.IntegerField(null=True, verbose_name='Вікова категорія')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('is_2d', models.BooleanField(default=False, verbose_name='2D')),
                ('is_3d', models.BooleanField(default=False, verbose_name='3D')),
                ('is_imax', models.BooleanField(default=False, verbose_name='IMAX')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='main.gallery', verbose_name='Галерея зображень')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.block_seo', verbose_name='Блок СЕО ')),
            ],
            options={
                'verbose_name': 'Кіно стрічка',
                'verbose_name_plural': 'Кіно стрічки',
            },
        ),
    ]
