# Generated by Django 5.1.7 on 2025-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='price',
            field=models.IntegerField(default=50, verbose_name='Цена'),
        ),
    ]
