# Generated by Django 5.1.7 on 2025-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата створення запису'),
        ),
    ]
