# Generated by Django 5.1.7 on 2025-07-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movies_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='price',
        ),
    ]
