# Generated by Django 5.1.7 on 2025-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_2d',
            field=models.BooleanField(default=False, verbose_name='2D'),
        ),
        migrations.AddField(
            model_name='movies',
            name='is_3d',
            field=models.BooleanField(default=False, verbose_name='2D'),
        ),
        migrations.AddField(
            model_name='movies',
            name='is_imax',
            field=models.BooleanField(default=False, verbose_name='2D'),
        ),
    ]
