# Generated by Django 5.1.7 on 2025-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movies_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='age_limit',
            field=models.PositiveIntegerField(verbose_name='Вікова категорія'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age_limit_ru',
            field=models.PositiveIntegerField(null=True, verbose_name='Вікова категорія'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age_limit_uk',
            field=models.PositiveIntegerField(null=True, verbose_name='Вікова категорія'),
        ),
    ]
