# Generated by Django 5.1.7 on 2025-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movies_is_2d_movies_is_3d_movies_is_imax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='video_type',
        ),
        migrations.AlterField(
            model_name='movies',
            name='is_3d',
            field=models.BooleanField(default=False, verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='is_imax',
            field=models.BooleanField(default=False, verbose_name='IMAX'),
        ),
    ]
