# Generated by Django 5.1.7 on 2025-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movies_video_type_alter_movies_is_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='age_limit_ru',
            field=models.IntegerField(null=True, verbose_name='Вікова категорія'),
        ),
        migrations.AddField(
            model_name='movies',
            name='age_limit_uk',
            field=models.IntegerField(null=True, verbose_name='Вікова категорія'),
        ),
        migrations.AddField(
            model_name='movies',
            name='date_ru',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата створення запису'),
        ),
        migrations.AddField(
            model_name='movies',
            name='date_uk',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата створення запису'),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис '),
        ),
        migrations.AddField(
            model_name='movies',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис '),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre_ru',
            field=models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11, null=True, verbose_name='Жанр '),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre_uk',
            field=models.CharField(choices=[('DR', 'Драма'), ('COM', 'Комедія'), ('ACT', 'Бойовик'), ('TR', 'Трилер'), ('HOR', 'Жахи'), ('Sci', 'Фантастика'), ('FAN', 'Фентезі')], max_length=11, null=True, verbose_name='Жанр '),
        ),
        migrations.AddField(
            model_name='movies',
            name='relise_date_ru',
            field=models.DateField(null=True, verbose_name='Дата проката'),
        ),
        migrations.AddField(
            model_name='movies',
            name='relise_date_uk',
            field=models.DateField(null=True, verbose_name='Дата проката'),
        ),
        migrations.AddField(
            model_name='movies',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='movies',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
    ]
