# Generated by Django 5.1.7 on 2025-06-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movies_description_alter_movies_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='date_ru',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='date_uk',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre_ru',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre_uk',
        ),
    ]
